In [5]:
import pandas as pd

# Carregar CSV com separador ";"
df_desmatamento = pd.read_csv("terrabrasilis_desmatamento_para.csv", sep=';', header=0)
df_desmatamento.columns = ['Município', 'Área_desmatada_km2', 'Codigo_IBGE', 'Estado']

# Substituir vírgula decimal por ponto e converter para float, ignorando erros
df_desmatamento['Área_desmatada_km2'] = df_desmatamento['Área_desmatada_km2'].str.replace('.', '', regex=False)
df_desmatamento['Área_desmatada_km2'] = df_desmatamento['Área_desmatada_km2'].str.replace(',', '.', regex=False)
df_desmatamento['Área_desmatada_km2'] = pd.to_numeric(df_desmatamento['Área_desmatada_km2'], errors='coerce')

# Remover linhas com valores NaN na coluna 'Área_desmatada_km2'
df_desmatamento = df_desmatamento.dropna(subset=['Área_desmatada_km2'])

# Conferir resultado
df_desmatamento.head()

# Conferir resultado
df_desmatamento.head()

            Município  Área_desmatada_km2  Codigo_IBGE Estado
0            Itaituba             2687.99      1503606   Pará
1        Jacareacanga              843.86      1503754   Pará
2  São Félix do Xingu             5937.22      1507300   Pará
3            Altamira             6611.69      1500602   Pará
4     Cumaru do Norte              799.53      1502764   Pará

In [8]:
def extrair_dados_socioeconomicos(arquivo_txt, nome_municipio):
    with open(arquivo_txt, encoding='utf-8') as f:
        linhas = f.readlines()

    dados = {
        "Município": nome_municipio,
        "Prefeito": "",
        "Área_Territorial_km2": None,
        "População_Censo": None,
        "Densidade_demográfica": None,
        "População_Estimada": None,
        "Escolarização_6_14_anos": None,
        "IDHM": None,
        "Mortalidade_infantil": None,
        "Receitas_R$": None,
        "Despesas_R$": None,
        "PIB_per_capita_R$": None
    }

    for linha in linhas:
        linha = linha.strip()
        if "Prefeito" in linha:
            dados["Prefeito"] = linha.split("-")[-1].strip()
        elif "Área Territorial" in linha:
            dados["Área_Territorial_km2"] = float(linha.split("-")[-1].split()[0].replace('.', '').replace(',', '.'))
        elif "População no último censo" in linha:
            dados["População_Censo"] = int(linha.split("-")[-1].split()[0].replace('.', ''))
        elif "Densidade demográfica" in linha:
            dados["Densidade_demográfica"] = float(linha.split("-")[-1].split()[0].replace(',', '.'))
        elif "População estimada" in linha:
            dados["População_Estimada"] = int(linha.split("-")[-1].split()[0].replace('.', ''))
        elif "Escolarização" in linha:
            dados["Escolarização_6_14_anos"] = float(linha.split("-")[-1].split()[0].replace(',', '.'))
        elif "IDHM" in linha:
            dados["IDHM"] = float(linha.split("-")[-1].split()[0].replace(',', '.'))
        elif "Mortalidade infantil" in linha:
            dados["Mortalidade_infantil"] = float(linha.split("-")[-1].split()[0].replace(',', '.'))
        elif "Total de receitas brutas realizadas" in linha:
            dados["Receitas_R$"] = float(linha.split("-")[-1].split()[0].replace('.', '').replace(',', '.'))
        elif "Total de despesas brutas empenhadas" in linha:
            dados["Despesas_R$"] = float(linha.split("-")[-1].split()[0].replace('.', '').replace(',', '.'))
        elif "PIB per capita" in linha:
            dados["PIB_per_capita_R$"] = float(linha.split("-")[-1].split()[0].replace('.', '').replace(',', '.'))

    return dados

In [10]:
cidades = {
    "Altamira": "altamira_ibge.csv",
    "São Félix do Xingu": "sãofelixxingu_ibge.csv",
    "Itaituba": "itaituba_ibge.csv",
    "Jacareanga": "jacareacanga_ibge.csv",
    "Cumaru do Norte": "cumuru_ibge.csv"
}

dados_cidades = []

for nome, arquivo in cidades.items():
    dados = extrair_dados_socioeconomicos(arquivo, nome)
    dados_cidades.append(dados)

df_ibge = pd.DataFrame(dados_cidades)

ValueError: could not convert string to float: 'Escolarização'

In [ ]:
df_final = pd.merge(df_desmatamento, df_ibge, on="Município")

# Exibir dados prontos para análise
df_final.head()